sonar.projectKey=standort-check
sonar.projectName=standort-check
sonar.sources=backend,cmd,api,frontend/src
sonar.tests=backend
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/node_modules/**,frontend/dist/**,**/*_test.go
sonar.sourceEncoding=UTF-8
sonar.go.coverage.reportPaths=coverage.out
